In [1]:
import pandas as pd

In [2]:
datos = pd.read_csv("C:/Users/WALTER/Downloads/Colombianos_registrados_en_el_exterior_20250412.csv", header=0) #base de datos colombianos en el exterior

In [3]:
datos.shape # se realiza funcion para conocer el numero de filas y columnas del archivo

(1672255, 17)

In [4]:
datos.info() #informacion acerca de la base de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1672255 entries, 0 to 1672254
Data columns (total 17 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   País                   1672255 non-null  object
 1   Código ISO país        1672255 non-null  object
 2   Ciudad de Residencia   1672255 non-null  object
 3   Oficina de registro    1672255 non-null  object
 4   Grupo edad             1672255 non-null  object
 5   Edad (años)            1672255 non-null  int64
 6   Área Conocimiento      1672255 non-null  object
 7   Sub Area Conocimiento  1672255 non-null  object
 8   Nivel Académico        1672255 non-null  object
 9   Estado civil           1672255 non-null  object
 10  Género                 1672255 non-null  object
 11  Etnia de la persona    1672255 non-null  object
 12  Estatura (CM)          1672255 non-null  int64
 13  Ciudad de Nacimiento   1672255 non-null  object
 14  Localización           1672255 non-null  object
 15  Fecha de Registro      1672255 non-null  object
 16  Cantidad de personas   1672255 non-null  int64
dtypes: int64(3), object(14)
memory usage: 216.9+ MB

In [5]:
datos # primeras 5 filas y ultimas 5 filas

,País,Código ISO país,Ciudad de Residencia,Oficina de registro,Grupo edad,Edad (años),Área Conocimiento,Sub Area Conocimiento,Nivel Académico,Estado civil,Género,Etnia de la persona,Estatura (CM),Ciudad de Nacimiento,Localización,Fecha de Registro,Cantidad de personas
0,MEXICO,MEX,NUEVO LEON/MONTERREY,C. MEXICO,ADOLESCENTE,16,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/ATLANTICO/BARRANQUILLA,"(23.634501, -102.552784)",2017-07,1
1,ALBANIA,ALB,TIRANE/FACESH,C. ROMA,DESCONOCIDO,-1,NO INDICA,NO INDICA,BACHILLERATO,DESCONOCIDO,FEMENINO,SIN ETNIA REGISTRADA,-1,COLOMBIA/ANTIOQUIA/ITAGUI,"(41.153332, 20.168331)",2015-10,1
2,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,NINGUNA,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-02,1
3,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-02,1
4,ECUADOR,ECU,PICHINCHA/QUITO,C. QUITO,ADULTO,52,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/CALDAS/SUPIA,"(-1.831239, -78.183406)",2016-08,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1672250,ESTADOS UNIDOS,USA,CALIFORNIA/ORANGEVALE,C. SAN FRANCISCO,ADULTO,56,CIENCIAS DE LA SALUD,ODONTOLOG�A,NO INDICA,CASADO,FEMENINO,NINGUNA,-1,COLOMBIA/VALLE DEL CAUCA/RESTREPO,"(37.09024, -95.712891)",2016-04,1
1672251,ESPA�A,ESP,MADRID/MADRID,C. MADRID,ADULTO,36,NINGUNA,NINGUNA,BACHILLERATO,CASADO,MASCULINO,AFRODESCENDIENTE,166,COLOMBIA/VALLE DEL CAUCA/PALMIRA,"(40.463667, -3.74922)",2014-11,1
1672252,ESTADOS UNIDOS,USA,NEW JERSEY/ENGLEWOOD,C. NEWARK,ADULTO MAYOR,62,NINGUNA,NINGUNA,NO INDICA,DIVORCIADO,FEMENINO,OTRO,-1,COLOMBIA/RISARALDA/APIA,"(37.09024, -95.712891)",2017-08,1
1672253,ESPA�A,ESP,MURCIA/JUMILLA,C. VALENCIA ESP,ADULTO MAYOR,63,NINGUNA,NINGUNA,NO INDICA,CASADO,MASCULINO,NINGUNA,-1,COLOMBIA/CALDAS/RISARALDA,"(40.463667, -3.74922)",2021-08,1
1672254,VENEZUELA,VEN,ZULIA/MARACAIBO,C. MARACAIBO,ADULTO,36,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,VENEZUELA/ZULIA/MARACAIBO,"(6.42375, -66.58973)",2018-08,3

In [6]:
datos.columns #nombres de las columnas

Index(['País', 'Código ISO país', 'Ciudad de Residencia',
       'Oficina de registro', 'Grupo edad', 'Edad (años)', 'Área Conocimiento',
       'Sub Area Conocimiento', 'Nivel Académico', 'Estado civil', 'Género',
       'Etnia de la persona', 'Estatura (CM)', 'Ciudad de Nacimiento',
       'Localización', 'Fecha de Registro', 'Cantidad de personas'],
      dtype='object')

In [7]:
datos.head(20) #devuelve numero de filas segun el valor que se asigne

,País,Código ISO país,Ciudad de Residencia,Oficina de registro,Grupo edad,Edad (años),Área Conocimiento,Sub Area Conocimiento,Nivel Académico,Estado civil,Género,Etnia de la persona,Estatura (CM),Ciudad de Nacimiento,Localización,Fecha de Registro,Cantidad de personas
0,MEXICO,MEX,NUEVO LEON/MONTERREY,C. MEXICO,ADOLESCENTE,16,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/ATLANTICO/BARRANQUILLA,"(23.634501, -102.552784)",2017-07,1
1,ALBANIA,ALB,TIRANE/FACESH,C. ROMA,DESCONOCIDO,-1,NO INDICA,NO INDICA,BACHILLERATO,DESCONOCIDO,FEMENINO,SIN ETNIA REGISTRADA,-1,COLOMBIA/ANTIOQUIA/ITAGUI,"(41.153332, 20.168331)",2015-10,1
2,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,NINGUNA,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-02,1
3,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-02,1
4,ECUADOR,ECU,PICHINCHA/QUITO,C. QUITO,ADULTO,52,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/CALDAS/SUPIA,"(-1.831239, -78.183406)",2016-08,1
5,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2024-07,1
6,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2023-03,1
7,CURA�AO,CUW,CURA�AO/WILLEMSTAD,C. WILLEMSTAD,ADULTO,46,NINGUNA,NINGUNA,BACHILLERATO,UNION_LIBRE,FEMENINO,OTRO,-1,COLOMBIA/ANTIOQUIA/ITAGUI,"(12.16957, -68.990021)",2023-03,1
8,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/HUILA/NEIVA,"(51.165691, 10.451526)",2021-10,1
9,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/ANTIOQUIA/MEDELLIN,"(51.165691, 10.451526)",2022-06,1
10,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2022-04,1
11,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,FRANCIA/ILE-DE-FRANCE/SAINT-MAUR-DES-FOSSES,"(51.165691, 10.451526)",2022-05,1
12,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,14,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,NINGUNA,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2022-06,1
13,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,14,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2021-12,1
14,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,14,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2022-06,1
15,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,14,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/QUINDIO/ARMENIA,"(51.165691, 10.451526)",2021-08,1
16,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,15,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2023-01,1
17,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,15,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2023-10,1
18,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,15,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN-PANKOW,"(51.165691, 10.451526)",2024-09,1
19,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,15,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/THURINGEN/WEIMAR,"(51.165691, 10.451526)",2021-08,1

In [8]:
datos.tail(20) #devuelve las ultimas filas segun el valor que se asigne

,País,Código ISO país,Ciudad de Residencia,Oficina de registro,Grupo edad,Edad (años),Área Conocimiento,Sub Area Conocimiento,Nivel Académico,Estado civil,Género,Etnia de la persona,Estatura (CM),Ciudad de Nacimiento,Localización,Fecha de Registro,Cantidad de personas
1672235,ESTADOS UNIDOS,USA,FLORIDA/SARASOTA,C. MIAMI,ADULTO,51,"ECONOM�A, ADMINISTRACI�N CONTADURIA Y AFINES",CONTADUR�A P�BLICA,NO INDICA,CASADO,MASCULINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(37.09024, -95.712891)",2017-07,1
1672236,ESTADOS UNIDOS,USA,FLORIDA/ORLANDO,C. ORLANDO,PRIMERA INFANCIA,5,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/ANTIOQUIA/MEDELLIN,"(37.09024, -95.712891)",2023-09,1
1672237,ESPA�A,ESP,MADRID/MADRID,C. MADRID,ADULTO,36,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(40.463667, -3.74922)",2024-07,1
1672238,VENEZUELA,VEN,CARABOBO/VALENCIA,C. VALENCIA VEN,ADULTO,38,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,OTRO,-1,VENEZUELA/CARABOBO/VALENCIA,"(6.42375, -66.58973)",2017-07,1
1672239,ESTADOS UNIDOS,USA,TEXAS/HOCKLEY,C. HOUSTON,ADULTO,48,CIENCIAS DE LA SALUD,TERAPIAS,PREGRADO - PROFESIONAL,CASADO,FEMENINO,OTRO,-1,COLOMBIA/VALLE DEL CAUCA/CALI,"(37.09024, -95.712891)",2025-02,1
1672240,ESPA�A,ESP,COMUNIDAD VALENCIANA/CASTELLON DE LA PLANA,C. VALENCIA ESP,ADULTO MAYOR,68,NO INDICA,NO INDICA,BACHILLERATO,SOLTERO,MASCULINO,NINGUNA,169,COLOMBIA/VALLE DEL CAUCA/BUGA,"(40.463667, -3.74922)",2015-05,1
1672241,ESTADOS UNIDOS,USA,CONNECTICUT/SEYMOUR,C. NUEVA YORK,ADULTO MAYOR,60,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,MASCULINO,NINGUNA,175,COLOMBIA/ANTIOQUIA/ITAGUI,"(37.09024, -95.712891)",2015-06,1
1672242,ESPA�A,ESP,MADRID/LEGANES,C. MADRID,ADULTO MAYOR,71,NINGUNA,NINGUNA,BACHILLERATO,DIVORCIADO,FEMENINO,NINGUNA,-1,COLOMBIA/QUINDIO/ARMENIA,"(40.463667, -3.74922)",2022-09,1
1672243,ESTADOS UNIDOS,USA,FLORIDA/MIAMI,C. MIAMI,ADULTO,53,"ECONOM�A, ADMINISTRACI�N CONTADURIA Y AFINES",CONTADUR�A P�BLICA,NO INDICA,CASADO,FEMENINO,NINGUNA,-1,COLOMBIA/ANTIOQUIA/MEDELLIN,"(37.09024, -95.712891)",2018-04,1
1672244,ESTADOS UNIDOS,USA,VIRGINIA/MANASSAS PARK,C. WASHINGTON,ADULTO,54,NINGUNA,NINGUNA,NINGUNO,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/ATLANTICO/BARRANQUILLA,"(37.09024, -95.712891)",2023-06,1
1672245,COSTA RICA,CRI,HEREDIA/BARVA,C. SAN JOSE,ADULTO,31,NINGUNA,NINGUNA,NO INDICA,SOLTERO,FEMENINO,NINGUNA,-1,COLOMBIA/VALLE DEL CAUCA/BUENAVENTURA,"(9.748917, -83.753428)",2022-08,1
1672246,NUEVA ZELANDA,NZL,AUCKLAND/AUCKLAND,C. AUCKLAND,ADULTO,38,CIENCIAS SOCIALES Y HUMANAS,PSICOLOG�A Y AFINES,NO INDICA,UNION_LIBRE,FEMENINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(-40.900557, 174.885971)",2018-10,1
1672247,ESPA�A,ESP,ANDALUCIA/GRANADA,C. SEVILLA,ADULTO,51,NINGUNA,NINGUNA,BACHILLERATO,SOLTERO,FEMENINO,OTRO,-1,COLOMBIA/ANTIOQUIA/ITAGUI,"(40.463667, -3.74922)",2020-07,1
1672248,ESPA�A,ESP,MADRID/COSLADA,C. MADRID,ADULTO JOVEN,20,NINGUNA,NINGUNA,PRIMARIA,UNION_LIBRE,FEMENINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOT� DC,"(40.463667, -3.74922)",2023-10,1
1672249,FEDERACION DE RUSIA,RUS,BELGOROD/BELGOROD,C. MOSCU,ADULTO JOVEN,23,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,NINGUNA,-1,COLOMBIA/CUNDINAMARCA/BOGOTA D.C.,"(61.52401, 105.318756)",2022-02,1
1672250,ESTADOS UNIDOS,USA,CALIFORNIA/ORANGEVALE,C. SAN FRANCISCO,ADULTO,56,CIENCIAS DE LA SALUD,ODONTOLOG�A,NO INDICA,CASADO,FEMENINO,NINGUNA,-1,COLOMBIA/VALLE DEL CAUCA/RESTREPO,"(37.09024, -95.712891)",2016-04,1
1672251,ESPA�A,ESP,MADRID/MADRID,C. MADRID,ADULTO,36,NINGUNA,NINGUNA,BACHILLERATO,CASADO,MASCULINO,AFRODESCENDIENTE,166,COLOMBIA/VALLE DEL CAUCA/PALMIRA,"(40.463667, -3.74922)",2014-11,1
1672252,ESTADOS UNIDOS,USA,NEW JERSEY/ENGLEWOOD,C. NEWARK,ADULTO MAYOR,62,NINGUNA,NINGUNA,NO INDICA,DIVORCIADO,FEMENINO,OTRO,-1,COLOMBIA/RISARALDA/APIA,"(37.09024, -95.712891)",2017-08,1
1672253,ESPA�A,ESP,MURCIA/JUMILLA,C. VALENCIA ESP,ADULTO MAYOR,63,NINGUNA,NINGUNA,NO INDICA,CASADO,MASCULINO,NINGUNA,-1,COLOMBIA/CALDAS/RISARALDA,"(40.463667, -3.74922)",2021-08,1
1672254,VENEZUELA,VEN,ZULIA/MARACAIBO,C. MARACAIBO,ADULTO,36,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,VENEZUELA/ZULIA/MARACAIBO,"(6.42375, -66.58973)",2018-08,3

In [9]:
datos.loc[0] #devuelve los encabezados y datos de la fila que se especifique

País                                              MEXICO
Código ISO país                                      MEX
Ciudad de Residencia                NUEVO LEON/MONTERREY
Oficina de registro                            C. MEXICO
Grupo edad                                   ADOLESCENTE
Edad (años)                                           16
Área Conocimiento                                NINGUNA
Sub Area Conocimiento                            NINGUNA
Nivel Académico                                NO INDICA
Estado civil                                     SOLTERO
Género                                         MASCULINO
Etnia de la persona                              NINGUNA
Estatura (CM)                                         -1
Ciudad de Nacimiento     COLOMBIA/ATLANTICO/BARRANQUILLA
Localización                    (23.634501, -102.552784)
Fecha de Registro                                2017-07
Cantidad de personas                                   1
Name: 0, dtype: object

In [10]:
datos.loc[[5,10]] # devuelve los datos en la fila 6 y 11

,País,Código ISO país,Ciudad de Residencia,Oficina de registro,Grupo edad,Edad (años),Área Conocimiento,Sub Area Conocimiento,Nivel Académico,Estado civil,Género,Etnia de la persona,Estatura (CM),Ciudad de Nacimiento,Localización,Fecha de Registro,Cantidad de personas
5,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,12,NINGUNA,NINGUNA,PRIMARIA,SOLTERO,FEMENINO,OTRO,-1,ALEMANIA/BERLIN/BERLIN,"(51.165691, 10.451526)",2024-07,1
10,ALEMANIA,DEU,BERLIN/BERLIN,C. BERLIN,ADOLESCENTE,13,NINGUNA,NINGUNA,NO INDICA,SOLTERO,MASCULINO,OTRO,-1,COLOMBIA/CUNDINAMARCA/BOGOTA,"(51.165691, 10.451526)",2022-04,1

In [11]:
datos.Género.describe() #se identifica que el genero que mas se encuentra en otros paises de colombia es el femenino

count      1672255
unique           4
top       FEMENINO
freq        914397
Name: Género, dtype: object

In [12]:
datos.País.describe() # se identifica que el pais con mas colombianos registrados es Estados Unidos

count            1672255
unique               194
top       ESTADOS UNIDOS
freq              492422
Name: País, dtype: object

In [13]:
datos["Edad (años)"].describe() # al identificar la columna edad como numero lo describe con datos estadisticos como la media

count    1.672255e+06
mean     4.387605e+01
std      1.673716e+01
min     -1.000000e+00
25%      3.200000e+01
50%      4.200000e+01
75%      5.500000e+01
max      1.390000e+02
Name: Edad (años), dtype: float64

In [ ]:
datos["Edad (años)"].median() #mediana, al menos el 50% de los colombianos en el exterior tiene 42 años o menos

np.float64(42.0)

In [14]:
datos["Edad (años)"].mean() #se identifica que la edad promedio de las personas residentes en otro pais es de 43 años

np.float64(43.876045818371004)

In [ ]:
#al observar el valor minimo como -1 en la edad se calcula el promedio sin ese valor ya que en edad no es dato real
edades_validas=datos[datos["Edad (años)"]>=0]
promedio = edades_validas["Edad (años)"].mean()
print(promedio)

43.9486730879463

In [ ]:
#al identificar que no se afecto casi el promedio los valores en -1 se cuentan y se observa que son pocos datos(2702), por lo mismo no afecta casi al total de datos que son mas de 1 millon
datos["Edad (años)"].value_counts().get(-1)

np.int64(2702)

In [ ]:
#descripcion columna ciudad de nacimiento
datos["Ciudad de Nacimiento"].describe()

count                          1672255
unique                           12325
top       COLOMBIA/CUNDINAMARCA/BOGOTA
freq                            232340
Name: Ciudad de Nacimiento, dtype: object

In [ ]:
#descripcion columna estado civil
datos["Estado civil"].describe()

count     1672255
unique          8
top       SOLTERO
freq       844376
Name: Estado civil, dtype: object

In [ ]:
#descripcion columna nivel academico
datos["Nivel Académico"].describe()

count       1672255
unique           17
top       NO INDICA
freq         757189
Name: Nivel Académico, dtype: object

In [ ]:
#descripcion columna Etnia de la persona
datos["Etnia de la persona"].describe()

count     1672255
unique          8
top          OTRO
freq       867516
Name: Etnia de la persona, dtype: object

In [46]:
#descripcion columna ciudad residencia
datos["Ciudad de Residencia"].describe()

count           1672255
unique            38983
top       MADRID/MADRID
freq              76920
Name: Ciudad de Residencia, dtype: object

In [ ]:
#descripcion columna Grupo edad
datos["Grupo edad"].describe()

count     1672255
unique          7
top        ADULTO
freq      1069873
Name: Grupo edad, dtype: object

In [ ]:
#descripcion columna Estatura
datos["Estatura (CM)"].describe()

count    1.672255e+06
mean     3.030981e+01
std      1.852304e+02
min     -1.000000e+00
25%     -1.000000e+00
50%     -1.000000e+00
75%     -1.000000e+00
max      1.631630e+05
Name: Estatura (CM), dtype: float64

In [59]:
#al validar que los datos no son acordes se hace el caculo del promedio teniendo en cuenta los valores mayores a cero
estatura_valida=datos[datos["Estatura (CM)"]>=0]
promedio_estatura = estatura_valida["Estatura (CM)"].mean()
print(promedio_estatura)

165.1525291952272

In [ ]:
#descripcion columna area de conocimiento
datos["Área Conocimiento"].describe()

count     1672255
unique         24
top       NINGUNA
freq       879290
Name: Área Conocimiento, dtype: object

In [ ]:
#valores unicos columna ciudad de nacimiento
datos["Ciudad de Nacimiento"].unique()

array(['COLOMBIA/ATLANTICO/BARRANQUILLA', 'COLOMBIA/ANTIOQUIA/ITAGUI',
       'ALEMANIA/BERLIN/BERLIN', ..., 'COLOMBIA/ARAUCA/LA FLORIDA',
       'ESTADOS UNIDOS/MINNESOTA/MANKATO', 'VENEZUELA/BARINAS/LA CREOLE'],
      shape=(12325,), dtype=object)

In [ ]:
#valores unicos columna ciudad de residencia
datos["Ciudad de Residencia"].unique()

array(['NUEVO LEON/MONTERREY', 'TIRANE/FACESH', 'BERLIN/BERLIN', ...,
       'ASTURIAS/SANTA EULALIA DE OSCOS', 'NORDLAND/HERNES',
       'ANTWERPEN/HOBOKEN'], shape=(38983,), dtype=object)

In [ ]:
#valores unicos columna Edad
datos["Edad (años)"].unique()

array([ 16,  -1,  12,  52,  46,  13,  14,  15,  17,  29,  57,  35,  30,
        22,  28,  31,  48,  32,  49,  60,  69,  71,  33,  42,  34,  39,
        36,  25,  38,  68,  55,  27,  53,  65,  74,  51,  37,  44,  58,
        87,  41,  40,  59,  18,  50,  43,  10,  73,  45,  47,   9,  54,
        56,  62,  19,  20,  21,  23,  24,  67,  82,  26,  64,  63,  72,
        75,  84,   8,  70,  11,   0,   1,   2,   3,   4,   5,  79,  80,
         7,  83,  66,  61,  77,  81,   6,  78,  76,  89,  94,  88,  85,
        92,  90,  96,  86,  97,  91,  95, 102,  93, 115, 103,  98,  99,
       109, 101, 111, 100, 105, 104, 110, 135, 106, 108, 107, 112, 113,
       114, 133, 125, 132, 139, 127, 131, 128, 121, 134, 120, 118, 116])

In [ ]:
#valores unicos columna Estado civil
datos["Estado civil"].unique()

array(['SOLTERO', 'DESCONOCIDO', 'UNION_LIBRE', 'CASADO', 'DIVORCIADO',
       'SEPARADO_MATRIMONIO', 'VIUDO', 'SEPARADO_UNION_LIBRE'],
      dtype=object)

In [ ]:
#valores unicos columna Estatura
datos["Estatura (CM)"].unique()

array([    -1,    175,    170,    171,    177,    182,    157,    161,
          165,    153,    158,    164,    191,    172,    169,    166,
          174,    155,    162,    180,    150,    173,    160,    163,
          152,    181,    167,    168,    176,    178,    156,    130,
          179,    154,    184,    187,    159,    183,    189,    185,
           80,    190,    127,    145,    186,     60,    110,    125,
          144,    108,     15,    140,     70,    149,    143,    141,
          188,    135,    115,    146,    120,    122,      1,    151,
          119,    192,    193,    148,     57,     67,     62,    194,
          100,    103,    118,     63,    195,     59,    139,     50,
          147,     16,    142,    117,     51,     81,     56,     89,
           85,     98,    105,    116,    128,     17,      0,     45,
           75,    112,     58,     76,     78,     66,     52,     95,
          121,     86,     93,    133,    200,    136,    134,     77,
          126,    138,     79,     74,    137,     90,     65,     99,
          131,    109,    124,     18,     48,    123,    114,     64,
           72,     19,     55,     82,     97,     84,    102,    129,
           71,    132,    205,    106,    196,    104,    113,     87,
           54,     92,     96,    197,     30,     91,     47,    510,
           94,    455,     53,     22,      4,     68,      5,    502,
            2,     42,    501,    198,    462,    202,    101,     73,
          264,     35,    107,     83,     23,     88,     61,     14,
           40,    210,    220,    111,     34,      6,    203,    199,
          314,    266,     69,    204,    280,    665,     11,    206,
           20,    500,    465,     46,    860, 163163,    201,     33,
          270,    271,    519,     25, 153153,     49,    516,     10,
        17070,    550,    453])

In [ ]:
#valores unicos columna Fecha de registro
datos["Fecha de Registro"].unique()

array(['2017-07', '2015-10', '2023-02', '2016-08', '2024-07', '2023-03',
       '2021-10', '2022-06', '2022-04', '2022-05', '2021-12', '2021-08',
       '2023-01', '2023-10', '2024-09', '2022-03', '2017-08', '2023-11',
       '2024-04', '2016-05', '2022-09', '2023-04', '2025-03', '2024-06',
       '2014-03', '2024-02', '2017-12', '2021-06', '2021-05', '2014-02',
       '2014-05', '2018-05', '2023-12', '2024-03', '2022-08', '2013-04',
       '2023-09', '2021-09', '2023-07', '2021-07', '2024-01', '2022-01',
       '2019-11', '2014-08', '2013-11', '2022-10', '2022-07', '2023-05',
       '2015-08', '2022-02', '2015-12', '2020-07', '2022-11', '2017-05',
       '2024-05', '2024-08', '2018-09', '2021-11', '2013-10', '2020-08',
       '2018-11', '2014-01', '2017-02', '2020-09', '2016-03', '2018-04',
       '2017-03', '2013-12', '2023-06', '2020-10', '2017-11', '2015-09',
       '2018-02', '2015-06', '2018-01', '2023-08', '2015-02', '2013-09',
       '2015-11', '2017-04', '2014-06', '2015-05', '2018-08', '2017-06',
       '2015-07', '2018-03', '2016-06', '2014-04', '2020-01', '2014-12',
       '2016-02', '2013-06', '2017-10', '2015-04', '2013-08', '2015-03',
       '2024-11', '2020-11', '2013-03', '2014-09', '2013-07', '2020-03',
       '2018-12', '2019-03', '2014-10', '2019-10', '2021-03', '2016-01',
       '2019-09', '2019-08', '2021-04', '2017-09', '2016-11', '2017-01',
       '2019-01', '2019-07', '2025-01', '2021-02', '2016-09', '2014-07',
       '2016-04', '2019-05', '2021-01', '2016-12', '2020-05', '2020-12',
       '2016-07', '2019-04', '2018-06', '2020-02', '2022-12', '2018-07',
       '2020-06', '2020-04', '2018-10', '2019-06', '2016-10', '2019-12',
       '2013-05', '2019-02', '2025-02', '1900-01', '2024-10', '2015-01',
       '2024-12', '2014-11', '2013-02', '2025-04'], dtype=object)

In [ ]:
#valores unicos columna Pais
datos["País"].unique()

array(['MEXICO', 'ALBANIA', 'ALEMANIA', 'ECUADOR', 'CURA�AO',
       'ESTADOS UNIDOS', 'ESPA�A', 'ARUBA', 'CANADA', 'FRANCIA',
       'AUSTRALIA', 'INDIA', 'VENEZUELA', 'CHILE', 'COSTA RICA',
       'RUMANIA', 'INDONESIA', 'REINO UNIDO', 'ARGENTINA',
       'NUEVA ZELANDA', 'BOLIVIA', 'ITALIA', 'PERU', 'DINAMARCA',
       'BRASIL', 'PANAMA', 'BELGICA', 'LIBANO', 'LUXEMBURGO', 'JAPON',
       'ANDORRA', 'PORTUGAL', 'SUIZA', 'EL SALVADOR', 'PAISES BAJOS',
       'ANGOLA', 'ANTIGUA Y BARBUDA', 'ANTILLAS HOLANDESAS', 'ISRAEL',
       'GRECIA', 'ARABIA SAUDITA', 'ARGELIA', 'FEDERACION DE RUSIA',
       'MALTA', 'REPUBLICA CHECA', 'REPUBLICA DOMINICANA', 'FINLANDIA',
       'GUATEMALA', 'SUECIA', 'AUSTRIA', 'PARAGUAY', 'URUGUAY',
       'EMIRATOS ARABES UNIDOS', 'ST. MAARTEN', 'CHINA', 'ESTONIA',
       'IRLANDA', 'UCRANIA', 'TURQUIA', 'BONAIRE', 'TRINIDAD Y TOBAGO',
       'ARMENIA', 'CUBA', 'NORUEGA', 'DESCONOCIDO', 'MARRUECOS',
       'AZERBAIYAN', 'COREA, REPUBLICA DE', 'POLONIA', 'GUYANA FRANCESA',
       'SINGAPUR', 'TAILANDIA', 'SAINT-MARTIN', 'MOZAMBIQUE', 'BAHAMAS',
       'BAHREIN', 'BANGLADESH', 'HONDURAS', 'BELICE', 'BERMUDAS',
       'BIELORRUSIA', 'LETONIA', 'HONG KONG', 'RUSIA', 'HUNGRIA',
       'SUDAFRICA', 'MALASIA', 'BULGARIA', 'CABO VERDE', 'CAMBOYA',
       'CAMERUN', 'QATAR', 'NICARAGUA', 'ESLOVENIA', 'HAITI', 'CROACIA',
       'PALESTINA', 'REPUBLICA DE CHINA-TAIWAN', 'KENIA', 'CHIPRE',
       'COREA, REPUBLICA DEMOCRATICA POPULAR DE', 'JORDANIA',
       'ESLOVAQUIA', 'ISLANDIA', 'EGIPTO', 'FILIPINAS',
       'LAO, REPUBLIC DEMOCRATICA POPULAR DE', 'VIET NAM', 'TUNEZ',
       'GUINEA ECUATORIAL', 'LITUANIA', 'OMAN', 'AFGANISTAN', 'MONGOLIA',
       'GHANA', 'MYANMAR', 'KUWAIT', 'BRUNEI DARUSSALAM', 'SURINAM',
       'ETIOPIA', 'BARBADOS', 'GABON', 'GEORGIA', 'UGANDA', 'IRAK',
       'IRAN, REPUBLICA ISLAMICA DE', 'ISLAS VIRGENES BRITANICAS',
       'JAMAICA', 'KAZAJSTAN', 'LIECHTENSTEIN', 'MADAGASCAR', 'MALI',
       'MARTINICA', 'MAURICIO', 'MOLDOVA, REPUBLICA DE', 'MONACO',
       'NIGER', 'NIGERIA', 'NUEVA CALEDONIA', 'PAKISTAN',
       'POLINESIA FRANCESA', 'BURKINA FASO', 'SANTO TOME Y PRINCIPE',
       'SENEGAL', 'SERBIA', 'SIRIA', 'SRI LANKA', 'SUDAN',
       'TANZANIA, REPUBLICA UNIDA DE', 'UZBEKISTAN',
       'CONGO, REPUBLICA DEMOCRATICA DE', 'FIJI', 'MONTENEGRO', 'YEMEN',
       'VIETNAM', 'GUYANA', 'CHINA, REP�BLICA POPULAR', 'MACAO', 'CONGO',
       'SAINT KITTS Y NEVIS', 'DOMINICA', 'LIBERIA', 'MALDIVAS',
       'SAN MARINO', 'MACEDONIA, EX REPUBLICA YUGOSLAVA DE',
       'SIERRA LEONA', 'BENIN', 'PAPUA NUEVA GUINEA',
       'REPUBLICA CENTROAFRICANA', 'KIRGUISTAN', 'KOSOVO',
       'ISLAS COMOROS', 'GROENLANDIA', 'SUDAN DEL SUR', 'GUADALUPE',
       'RUANDA', 'COSTA DE MARFIL', 'GUINEA', 'BOSNIA Y HERZEGOVINA',
       'TOGO', 'MALAWI', 'NAMIBIA', 'BURUNDI', 'SANTA LUCIA', 'VANUATU',
       'SUAZILANDIA', 'REPUBLICA ARABE SIRIA', 'GRANADA',
       'SAN VICENTE Y LAS GRANADINAS', 'MAURITANIA', 'BOTSUANA',
       'GUINEA-BISSAU', 'BUTAN', 'ZAMBIA'], dtype=object)